#!/usr/bin/env bash
# ============================================================================
# xStock — application setup (run on the VPS, as the app user, after provision)
# ----------------------------------------------------------------------------
#   bash deploy/setup-app.sh
#
# Writes the production .env files, installs dependencies, generates the Prisma
# client, applies migrations, (optionally) seeds, and builds both apps.
# Idempotent. Run again any time config changes (or just use deploy.sh later).
# ============================================================================
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
load_env
load_node_runtime
require_vars WMS_DOMAIN DB_NAME DB_USER DB_PASSWORD JWT_SECRET BACKEND_PORT

command -v node >/dev/null || die "node not found. Run deploy/provision.sh first (or open a new shell so nvm loads)."

DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"
REDIS_URL="redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}"

# ---------------------------------------------------------------------------
step "Writing backend/.env"
cat > "${APP_DIR}/backend/.env" <<EOF
# Generated by deploy/setup-app.sh — do not commit.
DATABASE_URL="${DATABASE_URL}"
JWT_SECRET="${JWT_SECRET}"
REDIS_URL="${REDIS_URL}"
RESEND_API_KEY="${RESEND_API_KEY:-}"
CORS_ORIGINS="https://${WMS_DOMAIN}"
PORT=${BACKEND_PORT}
HOST=127.0.0.1
SEED_ADMIN_PASSWORD="${SEED_ADMIN_PASSWORD:-password123}"
EOF
chmod 600 "${APP_DIR}/backend/.env"

step "Writing frontend/.env (NEXT_PUBLIC_API_URL is baked in at build time)"
cat > "${APP_DIR}/frontend/.env" <<EOF
# Generated by deploy/setup-app.sh — do not commit.
NEXT_PUBLIC_API_URL="https://${WMS_DOMAIN}/api"
EOF
chmod 600 "${APP_DIR}/frontend/.env"

export DATABASE_URL  # so Prisma/seed use it deterministically

# ---------------------------------------------------------------------------
step "Backend: install + Prisma client + migrate"
cd "${APP_DIR}/backend"
npm install
npx prisma generate
npx prisma migrate deploy

if [ "${RUN_SEED:-false}" = "true" ]; then
  step "Backend: seeding database (idempotent)"
  SEED_ADMIN_PASSWORD="${SEED_ADMIN_PASSWORD:-password123}" npm run seed
else
  c_ylw "RUN_SEED is not 'true' — skipping seed."
fi

step "Backend: build (compiles to dist/src/main.js)"
npm run build
mkdir -p "${APP_DIR}/backend/uploads"   # static upload target served at /uploads
[ -f "${APP_DIR}/backend/dist/src/main.js" ] || die "Backend build did not produce dist/src/main.js"

# ---------------------------------------------------------------------------
step "Frontend: install + build"
cd "${APP_DIR}/frontend"
# The darwin-only SWC dep in package.json is skipped on Linux; Next pulls the
# correct linux SWC binary automatically.
npm install
npm run build

echo
c_grn "App setup complete."
echo "  • Backend entry: ${APP_DIR}/backend/dist/src/main.js  (port ${BACKEND_PORT}, 127.0.0.1)"
echo "  • Frontend:      next start  (port ${FRONTEND_PORT}, 127.0.0.1)"
echo "  • Next:          bash deploy/nginx-setup.sh   then   start PM2 (see DEPLOYMENT.md)"
